from typing import List

class IStoragePort:
    def list_local(self) -> List[str]: ...
    def list_remote(self) -> List[str]: ...
    def download(self, remote_path: str, local_path: str) -> None: ...
    def upload(self, local_path: str, remote_path: str) -> None: ...

    def stat_local(self, file) -> float: ... # last modified timestamp
    def stat_remote(self, file) -> float: ...
